export const fonts = [
  "System Font / System Default Sans Serif",
  "System Font / Monospace",
  "System Font / Calibri, Candara, Segoe",
  "System Font / Century Gothic, AppleGothic",
  "System Font / Gill Sans, Calibri",
  "System Font / Tahoma, Verdana, Segoe",
  "System Font / Trebuchet MS, Lucida Grande",
  "System Font / Verdana, Geneva",
  "System Font / Book Antiqua, Palatino",
  "System Font / Cambria, Georgia, Times New Roman",
  "System Font / Garamond, Baskerville",
  "System Font / Georgia, Times",
  "System Font / Goudy Old Style, Garamond, Big Caslon",
  "System Font / Lucida Bright, Georgia",
  "System Font / Palatino, Palatino Linotype, Book Antiqua",
  "System Font / Baskerville, Hoefler Text, Garamond",
  "System Font / Times New Roman",
  "System Font / Courier New, Lucida Sans Typewriter",
  "System Font / Lucida Sans Typewriter, monaco, Bitstream Vera Sans Mono",
  "System Font / Copperplate",
  "Google Font / Abel",
  "Google Font / Abhaya Libre",
  "Google Font / Abril Fatface",
  "Google Font / Aclonica",
  "Google Font / Acme",
  "Google Font / Actor",
  "Google Font / Adamina",
  "Google Font / Advent Pro",
  "Google Font / Aguafina Script",
  "Google Font / Akronim",
  "Google Font / Aladin",
  "Google Font / Aldrich",
  "Google Font / Alef",
  "Google Font / Alegreya",
  "Google Font / Alegreya SC",
  "Google Font / Alegreya Sans",
  "Google Font / Alegreya Sans SC",
  "Google Font / Aleo",
  "Google Font / Alex Brush",
  "Google Font / Alfa Slab One",
  "Google Font / Alice",
  "Google Font / Alike",
  "Google Font / Alike Angular",
  "Google Font / Allan",
  "Google Font / Allerta",
  "Google Font / Allerta Stencil",
  "Google Font / Allura",
  "Google Font / Almarai",
  "Google Font / Almendra",
  "Google Font / Almendra Display",
  "Google Font / Almendra SC",
  "Google Font / Amarante",
  "Google Font / Amaranth",
  "Google Font / Amatic SC",
  "Google Font / Amethysta",
  "Google Font / Amiko",
  "Google Font / Amiri",
  "Google Font / Amita",
  "Google Font / Anaheim",
  "Google Font / Andada",
  "Google Font / Andika",
  "Google Font / Angkor",
  "Google Font / Annie Use Your Telescope",
  "Google Font / Anonymous Pro",
  "Google Font / Antic",
  "Google Font / Antic Didone",
  "Google Font / Antic Slab",
  "Google Font / Anton",
  "Google Font / Arapey",
  "Google Font / Arbutus",
  "Google Font / Arbutus Slab",
  "Google Font / Architects Daughter",
  "Google Font / Archivo",
  "Google Font / Archivo Black",
  "Google Font / Archivo Narrow",
  "Google Font / Aref Ruqaa",
  "Google Font / Arima Madurai",
  "Google Font / Arimo",
  "Google Font / Arizonia",
  "Google Font / Armata",
  "Google Font / Arsenal",
  "Google Font / Artifika",
  "Google Font / Arvo",
  "Google Font / Arya",
  "Google Font / Asap",
  "Google Font / Asap Condensed",
  "Google Font / Asar",
  "Google Font / Asset",
  "Google Font / Assistant",
  "Google Font / Astloch",
  "Google Font / Asul",
  "Google Font / Athiti",
  "Google Font / Atma",
  "Google Font / Atomic Age",
  "Google Font / Aubrey",
  "Google Font / Audiowide",
  "Google Font / Autour One",
  "Google Font / Average",
  "Google Font / Average Sans",
  "Google Font / Averia Gruesa Libre",
  "Google Font / Averia Libre",
  "Google Font / Averia Sans Libre",
  "Google Font / Averia Serif Libre",
  "Google Font / B612",
  "Google Font / B612 Mono",
  "Google Font / Bad Script",
  "Google Font / Bahiana",
  "Google Font / Bahianita",
  "Google Font / Bai Jamjuree",
  "Google Font / Baloo",
  "Google Font / Baloo Bhai",
  "Google Font / Baloo Bhaijaan",
  "Google Font / Baloo Bhaina",
  "Google Font / Baloo Chettan",
  "Google Font / Baloo Da",
  "Google Font / Baloo Paaji",
  "Google Font / Baloo Tamma",
  "Google Font / Baloo Tammudu",
  "Google Font / Baloo Thambi",
  "Google Font / Balthazar",
  "Google Font / Bangers",
  "Google Font / Barlow",
  "Google Font / Barlow Condensed",
  "Google Font / Barlow Semi Condensed",
  "Google Font / Barriecito",
  "Google Font / Barrio",
  "Google Font / Basic",
  "Google Font / Battambang",
  "Google Font / Baumans",
  "Google Font / Bayon",
  "Google Font / Be Vietnam",
  "Google Font / Bebas Neue",
  "Google Font / Belgrano",
  "Google Font / Bellefair",
  "Google Font / Belleza",
  "Google Font / BenchNine",
  "Google Font / Bentham",
  "Google Font / Berkshire Swash",
  "Google Font / Beth Ellen",
  "Google Font / Bevan",
  "Google Font / Big Shoulders Display",
  "Google Font / Big Shoulders Text",
  "Google Font / Bigelow Rules",
  "Google Font / Bigshot One",
  "Google Font / Bilbo",
  "Google Font / Bilbo Swash Caps",
  "Google Font / BioRhyme",
  "Google Font / BioRhyme Expanded",
  "Google Font / Biryani",
  "Google Font / Bitter",
  "Google Font / Black And White Picture",
  "Google Font / Black Han Sans",
  "Google Font / Black Ops One",
  "Google Font / Blinker",
  "Google Font / Bokor",
  "Google Font / Bonbon",
  "Google Font / Boogaloo",
  "Google Font / Bowlby One",
  "Google Font / Bowlby One SC",
  "Google Font / Brawler",
  "Google Font / Bree Serif",
  "Google Font / Bubblegum Sans",
  "Google Font / Bubbler One",
  "Google Font / Buda",
  "Google Font / Buenard",
  "Google Font / Bungee",
  "Google Font / Bungee Hairline",
  "Google Font / Bungee Inline",
  "Google Font / Bungee Outline",
  "Google Font / Bungee Shade",
  "Google Font / Butcherman",
  "Google Font / Butterfly Kids",
  "Google Font / Cabin",
  "Google Font / Cabin Condensed",
  "Google Font / Cabin Sketch",
  "Google Font / Caesar Dressing",
  "Google Font / Cagliostro",
  "Google Font / Cairo",
  "Google Font / Calligraffitti",
  "Google Font / Cambay",
  "Google Font / Cambo",
  "Google Font / Candal",
  "Google Font / Cantarell",
  "Google Font / Cantata One",
  "Google Font / Cantora One",
  "Google Font / Capriola",
  "Google Font / Cardo",
  "Google Font / Carme",
  "Google Font / Carrois Gothic",
  "Google Font / Carrois Gothic SC",
  "Google Font / Carter One",
  "Google Font / Catamaran",
  "Google Font / Caudex",
  "Google Font / Caveat",
  "Google Font / Caveat Brush",
  "Google Font / Cedarville Cursive",
  "Google Font / Ceviche One",
  "Google Font / Chakra Petch",
  "Google Font / Changa",
  "Google Font / Changa One",
  "Google Font / Chango",
  "Google Font / Charm",
  "Google Font / Charmonman",
  "Google Font / Chathura",
  "Google Font / Chau Philomene One",
  "Google Font / Chela One",
  "Google Font / Chelsea Market",
  "Google Font / Chenla",
  "Google Font / Cherry Cream Soda",
  "Google Font / Cherry Swash",
  "Google Font / Chewy",
  "Google Font / Chicle",
  "Google Font / Chilanka",
  "Google Font / Chivo",
  "Google Font / Chonburi",
  "Google Font / Cinzel",
  "Google Font / Cinzel Decorative",
  "Google Font / Clicker Script",
  "Google Font / Coda",
  "Google Font / Coda Caption",
  "Google Font / Codystar",
  "Google Font / Coiny",
  "Google Font / Combo",
  "Google Font / Comfortaa",
  "Google Font / Coming Soon",
  "Google Font / Concert One",
  "Google Font / Condiment",
  "Google Font / Content",
  "Google Font / Contrail One",
  "Google Font / Convergence",
  "Google Font / Cookie",
  "Google Font / Copse",
  "Google Font / Corben",
  "Google Font / Cormorant",
  "Google Font / Cormorant Garamond",
  "Google Font / Cormorant Infant",
  "Google Font / Cormorant SC",
  "Google Font / Cormorant Unicase",
  "Google Font / Cormorant Upright",
  "Google Font / Courgette",
  "Google Font / Cousine",
  "Google Font / Coustard",
  "Google Font / Covered By Your Grace",
  "Google Font / Crafty Girls",
  "Google Font / Creepster",
  "Google Font / Crete Round",
  "Google Font / Crimson Pro",
  "Google Font / Crimson Text",
  "Google Font / Croissant One",
  "Google Font / Crushed",
  "Google Font / Cuprum",
  "Google Font / Cute Font",
  "Google Font / Cutive",
  "Google Font / Cutive Mono",
  "Google Font / DM Sans",
  "Google Font / DM Serif Display",
  "Google Font / DM Serif Text",
  "Google Font / Damion",
  "Google Font / Dancing Script",
  "Google Font / Dangrek",
  "Google Font / Darker Grotesque",
  "Google Font / David Libre",
  "Google Font / Dawning of a New Day",
  "Google Font / Days One",
  "Google Font / Dekko",
  "Google Font / Delius",
  "Google Font / Delius Swash Caps",
  "Google Font / Delius Unicase",
  "Google Font / Della Respira",
  "Google Font / Denk One",
  "Google Font / Devonshire",
  "Google Font / Dhurjati",
  "Google Font / Didact Gothic",
  "Google Font / Diplomata",
  "Google Font / Diplomata SC",
  "Google Font / Do Hyeon",
  "Google Font / Dokdo",
  "Google Font / Domine",
  "Google Font / Donegal One",
  "Google Font / Doppio One",
  "Google Font / Dorsa",
  "Google Font / Dosis",
  "Google Font / Dr Sugiyama",
  "Google Font / Duru Sans",
  "Google Font / Dynalight",
  "Google Font / EB Garamond",
  "Google Font / Eagle Lake",
  "Google Font / East Sea Dokdo",
  "Google Font / Eater",
  "Google Font / Economica",
  "Google Font / Eczar",
  "Google Font / El Messiri",
  "Google Font / Electrolize",
  "Google Font / Elsie",
  "Google Font / Elsie Swash Caps",
  "Google Font / Emblema One",
  "Google Font / Emilys Candy",
  "Google Font / Encode Sans",
  "Google Font / Encode Sans Condensed",
  "Google Font / Encode Sans Expanded",
  "Google Font / Encode Sans Semi Condensed",
  "Google Font / Encode Sans Semi Expanded",
  "Google Font / Engagement",
  "Google Font / Englebert",
  "Google Font / Enriqueta",
  "Google Font / Erica One",
  "Google Font / Esteban",
  "Google Font / Euphoria Script",
  "Google Font / Ewert",
  "Google Font / Exo",
  "Google Font / Exo 2",
  "Google Font / Expletus Sans",
  "Google Font / Fahkwang",
  "Google Font / Fanwood Text",
  "Google Font / Farro",
  "Google Font / Farsan",
  "Google Font / Fascinate",
  "Google Font / Fascinate Inline",
  "Google Font / Faster One",
  "Google Font / Fasthand",
  "Google Font / Fauna One",
  "Google Font / Faustina",
  "Google Font / Federant",
  "Google Font / Federo",
  "Google Font / Felipa",
  "Google Font / Fenix",
  "Google Font / Finger Paint",
  "Google Font / Fira Code",
  "Google Font / Fira Mono",
  "Google Font / Fira Sans",
  "Google Font / Fira Sans Condensed",
  "Google Font / Fira Sans Extra Condensed",
  "Google Font / Fjalla One",
  "Google Font / Fjord One",
  "Google Font / Flamenco",
  "Google Font / Flavors",
  "Google Font / Fondamento",
  "Google Font / Fontdiner Swanky",
  "Google Font / Forum",
  "Google Font / Francois One",
  "Google Font / Frank Ruhl Libre",
  "Google Font / Freckle Face",
  "Google Font / Fredericka the Great",
  "Google Font / Fredoka One",
  "Google Font / Freehand",
  "Google Font / Fresca",
  "Google Font / Frijole",
  "Google Font / Fruktur",
  "Google Font / Fugaz One",
  "Google Font / GFS Didot",
  "Google Font / GFS Neohellenic",
  "Google Font / Gabriela",
  "Google Font / Gaegu",
  "Google Font / Gafata",
  "Google Font / Galada",
  "Google Font / Galdeano",
  "Google Font / Galindo",
  "Google Font / Gamja Flower",
  "Google Font / Gayathri",
  "Google Font / Gentium Basic",
  "Google Font / Gentium Book Basic",
  "Google Font / Geo",
  "Google Font / Geostar",
  "Google Font / Geostar Fill",
  "Google Font / Germania One",
  "Google Font / Gidugu",
  "Google Font / Gilda Display",
  "Google Font / Give You Glory",
  "Google Font / Glass Antiqua",
  "Google Font / Glegoo",
  "Google Font / Gloria Hallelujah",
  "Google Font / Goblin One",
  "Google Font / Gochi Hand",
  "Google Font / Gorditas",
  "Google Font / Gothic A1",
  "Google Font / Goudy Bookletter 1911",
  "Google Font / Graduate",
  "Google Font / Grand Hotel",
  "Google Font / Gravitas One",
  "Google Font / Great Vibes",
  "Google Font / Grenze",
  "Google Font / Griffy",
  "Google Font / Gruppo",
  "Google Font / Gudea",
  "Google Font / Gugi",
  "Google Font / Gurajada",
  "Google Font / Habibi",
  "Google Font / Halant",
  "Google Font / Hammersmith One",
  "Google Font / Hanalei",
  "Google Font / Hanalei Fill",
  "Google Font / Handlee",
  "Google Font / Hanuman",
  "Google Font / Happy Monkey",
  "Google Font / Harmattan",
  "Google Font / Headland One",
  "Google Font / Heebo",
  "Google Font / Henny Penny",
  "Google Font / Hepta Slab",
  "Google Font / Herr Von Muellerhoff",
  "Google Font / Hi Melody",
  "Google Font / Hind",
  "Google Font / Hind Guntur",
  "Google Font / Hind Madurai",
  "Google Font / Hind Siliguri",
  "Google Font / Hind Vadodara",
  "Google Font / Holtwood One SC",
  "Google Font / Homemade Apple",
  "Google Font / Homenaje",
  "Google Font / IBM Plex Mono",
  "Google Font / IBM Plex Sans",
  "Google Font / IBM Plex Sans Condensed",
  "Google Font / IBM Plex Serif",
  "Google Font / IM Fell DW Pica",
  "Google Font / IM Fell DW Pica SC",
  "Google Font / IM Fell Double Pica",
  "Google Font / IM Fell Double Pica SC",
  "Google Font / IM Fell English",
  "Google Font / IM Fell English SC",
  "Google Font / IM Fell French Canon",
  "Google Font / IM Fell French Canon SC",
  "Google Font / IM Fell Great Primer",
  "Google Font / IM Fell Great Primer SC",
  "Google Font / Iceberg",
  "Google Font / Iceland",
  "Google Font / Imprima",
  "Google Font / Inconsolata",
  "Google Font / Inder",
  "Google Font / Indie Flower",
  "Google Font / Inika",
  "Google Font / Inknut Antiqua",
  "Google Font / Irish Grover",
  "Google Font / Istok Web",
  "Google Font / Italiana",
  "Google Font / Italianno",
  "Google Font / Itim",
  "Google Font / Jacques Francois",
  "Google Font / Jacques Francois Shadow",
  "Google Font / Jaldi",
  "Google Font / Jim Nightshade",
  "Google Font / Jockey One",
  "Google Font / Jolly Lodger",
  "Google Font / Jomhuria",
  "Google Font / Jomolhari",
  "Google Font / Josefin Sans",
  "Google Font / Josefin Slab",
  "Google Font / Joti One",
  "Google Font / Jua",
  "Google Font / Judson",
  "Google Font / Julee",
  "Google Font / Julius Sans One",
  "Google Font / Junge",
  "Google Font / Jura",
  "Google Font / Just Another Hand",
  "Google Font / Just Me Again Down Here",
  "Google Font / K2D",
  "Google Font / Kadwa",
  "Google Font / Kalam",
  "Google Font / Kameron",
  "Google Font / Kanit",
  "Google Font / Kantumruy",
  "Google Font / Karla",
  "Google Font / Karma",
  "Google Font / Katibeh",
  "Google Font / Kaushan Script",
  "Google Font / Kavivanar",
  "Google Font / Kavoon",
  "Google Font / Kdam Thmor",
  "Google Font / Keania One",
  "Google Font / Kelly Slab",
  "Google Font / Kenia",
  "Google Font / Khand",
  "Google Font / Khmer",
  "Google Font / Khula",
  "Google Font / Kirang Haerang",
  "Google Font / Kite One",
  "Google Font / Knewave",
  "Google Font / KoHo",
  "Google Font / Kodchasan",
  "Google Font / Kosugi",
  "Google Font / Kosugi Maru",
  "Google Font / Kotta One",
  "Google Font / Koulen",
  "Google Font / Kranky",
  "Google Font / Kreon",
  "Google Font / Kristi",
  "Google Font / Krona One",
  "Google Font / Krub",
  "Google Font / Kulim Park",
  "Google Font / Kumar One",
  "Google Font / Kumar One Outline",
  "Google Font / Kurale",
  "Google Font / La Belle Aurore",
  "Google Font / Lacquer",
  "Google Font / Laila",
  "Google Font / Lakki Reddy",
  "Google Font / Lalezar",
  "Google Font / Lancelot",
  "Google Font / Lateef",
  "Google Font / Lato",
  "Google Font / League Script",
  "Google Font / Leckerli One",
  "Google Font / Ledger",
  "Google Font / Lekton",
  "Google Font / Lemon",
  "Google Font / Lemonada",
  "Google Font / Lexend Deca",
  "Google Font / Lexend Exa",
  "Google Font / Lexend Giga",
  "Google Font / Lexend Mega",
  "Google Font / Lexend Peta",
  "Google Font / Lexend Tera",
  "Google Font / Lexend Zetta",
  "Google Font / Libre Barcode 128",
  "Google Font / Libre Barcode 128 Text",
  "Google Font / Libre Barcode 39",
  "Google Font / Libre Barcode 39 Extended",
  "Google Font / Libre Barcode 39 Extended Text",
  "Google Font / Libre Barcode 39 Text",
  "Google Font / Libre Baskerville",
  "Google Font / Libre Caslon Display",
  "Google Font / Libre Caslon Text",
  "Google Font / Libre Franklin",
  "Google Font / Life Savers",
  "Google Font / Lilita One",
  "Google Font / Lily Script One",
  "Google Font / Limelight",
  "Google Font / Linden Hill",
  "Google Font / Literata",
  "Google Font / Liu Jian Mao Cao",
  "Google Font / Livvic",
  "Google Font / Lobster",
  "Google Font / Lobster Two",
  "Google Font / Londrina Outline",
  "Google Font / Londrina Shadow",
  "Google Font / Londrina Sketch",
  "Google Font / Londrina Solid",
  "Google Font / Long Cang",
  "Google Font / Lora",
  "Google Font / Love Ya Like A Sister",
  "Google Font / Loved by the King",
  "Google Font / Lovers Quarrel",
  "Google Font / Luckiest Guy",
  "Google Font / Lusitana",
  "Google Font / Lustria",
  "Google Font / M PLUS 1p",
  "Google Font / M PLUS Rounded 1c",
  "Google Font / Ma Shan Zheng",
  "Google Font / Macondo",
  "Google Font / Macondo Swash Caps",
  "Google Font / Mada",
  "Google Font / Magra",
  "Google Font / Maiden Orange",
  "Google Font / Maitree",
  "Google Font / Major Mono Display",
  "Google Font / Mako",
  "Google Font / Mali",
  "Google Font / Mallanna",
  "Google Font / Mandali",
  "Google Font / Manjari",
  "Google Font / Mansalva",
  "Google Font / Manuale",
  "Google Font / Marcellus",
  "Google Font / Marcellus SC",
  "Google Font / Marck Script",
  "Google Font / Margarine",
  "Google Font / Markazi Text",
  "Google Font / Marko One",
  "Google Font / Marmelad",
  "Google Font / Martel",
  "Google Font / Martel Sans",
  "Google Font / Marvel",
  "Google Font / Mate",
  "Google Font / Mate SC",
  "Google Font / Material Icons",
  "Google Font / Maven Pro",
  "Google Font / McLaren",
  "Google Font / Meddon",
  "Google Font / MedievalSharp",
  "Google Font / Medula One",
  "Google Font / Meera Inimai",
  "Google Font / Megrim",
  "Google Font / Meie Script",
  "Google Font / Merienda",
  "Google Font / Merienda One",
  "Google Font / Merriweather",
  "Google Font / Merriweather Sans",
  "Google Font / Metal",
  "Google Font / Metal Mania",
  "Google Font / Metamorphous",
  "Google Font / Metrophobic",
  "Google Font / Michroma",
  "Google Font / Milonga",
  "Google Font / Miltonian",
  "Google Font / Miltonian Tattoo",
  "Google Font / Mina",
  "Google Font / Miniver",
  "Google Font / Miriam Libre",
  "Google Font / Mirza",
  "Google Font / Miss Fajardose",
  "Google Font / Mitr",
  "Google Font / Modak",
  "Google Font / Modern Antiqua",
  "Google Font / Mogra",
  "Google Font / Molengo",
  "Google Font / Molle",
  "Google Font / Monda",
  "Google Font / Monofett",
  "Google Font / Monoton",
  "Google Font / Monsieur La Doulaise",
  "Google Font / Montaga",
  "Google Font / Montez",
  "Google Font / Montserrat",
  "Google Font / Montserrat Alternates",
  "Google Font / Montserrat Subrayada",
  "Google Font / Moul",
  "Google Font / Moulpali",
  "Google Font / Mountains of Christmas",
  "Google Font / Mouse Memoirs",
  "Google Font / Mr Bedfort",
  "Google Font / Mr Dafoe",
  "Google Font / Mr De Haviland",
  "Google Font / Mrs Saint Delafield",
  "Google Font / Mrs Sheppards",
  "Google Font / Mukta",
  "Google Font / Mukta Mahee",
  "Google Font / Mukta Malar",
  "Google Font / Mukta Vaani",
  "Google Font / Muli",
  "Google Font / Mystery Quest",
  "Google Font / NTR",
  "Google Font / Nanum Brush Script",
  "Google Font / Nanum Gothic",
  "Google Font / Nanum Gothic Coding",
  "Google Font / Nanum Myeongjo",
  "Google Font / Nanum Pen Script",
  "Google Font / Neucha",
  "Google Font / Neuton",
  "Google Font / New Rocker",
  "Google Font / News Cycle",
  "Google Font / Niconne",
  "Google Font / Niramit",
  "Google Font / Nixie One",
  "Google Font / Nobile",
  "Google Font / Nokora",
  "Google Font / Norican",
  "Google Font / Nosifer",
  "Google Font / Notable",
  "Google Font / Nothing You Could Do",
  "Google Font / Noticia Text",
  "Google Font / Noto Sans",
  "Google Font / Noto Sans HK",
  "Google Font / Noto Sans JP",
  "Google Font / Noto Sans KR",
  "Google Font / Noto Sans SC",
  "Google Font / Noto Sans TC",
  "Google Font / Noto Serif",
  "Google Font / Noto Serif JP",
  "Google Font / Noto Serif KR",
  "Google Font / Noto Serif SC",
  "Google Font / Noto Serif TC",
  "Google Font / Nova Cut",
  "Google Font / Nova Flat",
  "Google Font / Nova Mono",
  "Google Font / Nova Oval",
  "Google Font / Nova Round",
  "Google Font / Nova Script",
  "Google Font / Nova Slim",
  "Google Font / Nova Square",
  "Google Font / Numans",
  "Google Font / Nunito",
  "Google Font / Nunito Sans",
  "Google Font / Odor Mean Chey",
  "Google Font / Offside",
  "Google Font / Old Standard TT",
  "Google Font / Oldenburg",
  "Google Font / Oleo Script",
  "Google Font / Oleo Script Swash Caps",
  "Google Font / Open Sans",
  "Google Font / Open Sans Condensed",
  "Google Font / Oranienbaum",
  "Google Font / Orbitron",
  "Google Font / Oregano",
  "Google Font / Orienta",
  "Google Font / Original Surfer",
  "Google Font / Oswald",
  "Google Font / Over the Rainbow",
  "Google Font / Overlock",
  "Google Font / Overlock SC",
  "Google Font / Overpass",
  "Google Font / Overpass Mono",
  "Google Font / Ovo",
  "Google Font / Oxanium",
  "Google Font / Oxygen",
  "Google Font / Oxygen Mono",
  "Google Font / PT Mono",
  "Google Font / PT Sans",
  "Google Font / PT Sans Caption",
  "Google Font / PT Sans Narrow",
  "Google Font / PT Serif",
  "Google Font / PT Serif Caption",
  "Google Font / Pacifico",
  "Google Font / Padauk",
  "Google Font / Palanquin",
  "Google Font / Palanquin Dark",
  "Google Font / Pangolin",
  "Google Font / Paprika",
  "Google Font / Parisienne",
  "Google Font / Passero One",
  "Google Font / Passion One",
  "Google Font / Pathway Gothic One",
  "Google Font / Patrick Hand",
  "Google Font / Patrick Hand SC",
  "Google Font / Pattaya",
  "Google Font / Patua One",
  "Google Font / Pavanam",
  "Google Font / Paytone One",
  "Google Font / Peddana",
  "Google Font / Peralta",
  "Google Font / Permanent Marker",
  "Google Font / Petit Formal Script",
  "Google Font / Petrona",
  "Google Font / Philosopher",
  "Google Font / Piedra",
  "Google Font / Pinyon Script",
  "Google Font / Pirata One",
  "Google Font / Plaster",
  "Google Font / Play",
  "Google Font / Playball",
  "Google Font / Playfair Display",
  "Google Font / Playfair Display SC",
  "Google Font / Podkova",
  "Google Font / Poiret One",
  "Google Font / Poller One",
  "Google Font / Poly",
  "Google Font / Pompiere",
  "Google Font / Pontano Sans",
  "Google Font / Poor Story",
  "Google Font / Poppins",
  "Google Font / Port Lligat Sans",
  "Google Font / Port Lligat Slab",
  "Google Font / Pragati Narrow",
  "Google Font / Prata",
  "Google Font / Preahvihear",
  "Google Font / Press Start 2P",
  "Google Font / Pridi",
  "Google Font / Princess Sofia",
  "Google Font / Prociono",
  "Google Font / Prompt",
  "Google Font / Prosto One",
  "Google Font / Proza Libre",
  "Google Font / Public Sans",
  "Google Font / Puritan",
  "Google Font / Purple Purse",
  "Google Font / Quando",
  "Google Font / Quantico",
  "Google Font / Quattrocento",
  "Google Font / Quattrocento Sans",
  "Google Font / Questrial",
  "Google Font / Quicksand",
  "Google Font / Quintessential",
  "Google Font / Qwigley",
  "Google Font / Racing Sans One",
  "Google Font / Radley",
  "Google Font / Rajdhani",
  "Google Font / Rakkas",
  "Google Font / Raleway",
  "Google Font / Raleway Dots",
  "Google Font / Ramabhadra",
  "Google Font / Ramaraja",
  "Google Font / Rambla",
  "Google Font / Rammetto One",
  "Google Font / Ranchers",
  "Google Font / Rancho",
  "Google Font / Ranga",
  "Google Font / Rasa",
  "Google Font / Rationale",
  "Google Font / Ravi Prakash",
  "Google Font / Red Hat Display",
  "Google Font / Red Hat Text",
  "Google Font / Redressed",
  "Google Font / Reem Kufi",
  "Google Font / Reenie Beanie",
  "Google Font / Revalia",
  "Google Font / Rhodium Libre",
  "Google Font / Ribeye",
  "Google Font / Ribeye Marrow",
  "Google Font / Righteous",
  "Google Font / Risque",
  "Google Font / Roboto",
  "Google Font / Roboto Condensed",
  "Google Font / Roboto Mono",
  "Google Font / Roboto Slab",
  "Google Font / Rochester",
  "Google Font / Rock Salt",
  "Google Font / Rokkitt",
  "Google Font / Romanesco",
  "Google Font / Ropa Sans",
  "Google Font / Rosario",
  "Google Font / Rosarivo",
  "Google Font / Rouge Script",
  "Google Font / Rozha One",
  "Google Font / Rubik",
  "Google Font / Rubik Mono One",
  "Google Font / Ruda",
  "Google Font / Rufina",
  "Google Font / Ruge Boogie",
  "Google Font / Ruluko",
  "Google Font / Rum Raisin",
  "Google Font / Ruslan Display",
  "Google Font / Russo One",
  "Google Font / Ruthie",
  "Google Font / Rye",
  "Google Font / Sacramento",
  "Google Font / Sahitya",
  "Google Font / Sail",
  "Google Font / Saira",
  "Google Font / Saira Condensed",
  "Google Font / Saira Extra Condensed",
  "Google Font / Saira Semi Condensed",
  "Google Font / Saira Stencil One",
  "Google Font / Salsa",
  "Google Font / Sanchez",
  "Google Font / Sancreek",
  "Google Font / Sansita",
  "Google Font / Sarabun",
  "Google Font / Sarala",
  "Google Font / Sarina",
  "Google Font / Sarpanch",
  "Google Font / Satisfy",
  "Google Font / Sawarabi Gothic",
  "Google Font / Sawarabi Mincho",
  "Google Font / Scada",
  "Google Font / Scheherazade",
  "Google Font / Schoolbell",
  "Google Font / Scope One",
  "Google Font / Seaweed Script",
  "Google Font / Secular One",
  "Google Font / Sedgwick Ave",
  "Google Font / Sedgwick Ave Display",
  "Google Font / Sevillana",
  "Google Font / Seymour One",
  "Google Font / Shadows Into Light",
  "Google Font / Shadows Into Light Two",
  "Google Font / Shanti",
  "Google Font / Share",
  "Google Font / Share Tech",
  "Google Font / Share Tech Mono",
  "Google Font / Shojumaru",
  "Google Font / Short Stack",
  "Google Font / Shrikhand",
  "Google Font / Siemreap",
  "Google Font / Sigmar One",
  "Google Font / Signika",
  "Google Font / Signika Negative",
  "Google Font / Simonetta",
  "Google Font / Single Day",
  "Google Font / Sintony",
  "Google Font / Sirin Stencil",
  "Google Font / Six Caps",
  "Google Font / Skranji",
  "Google Font / Slabo 13px",
  "Google Font / Slabo 27px",
  "Google Font / Slackey",
  "Google Font / Smokum",
  "Google Font / Smythe",
  "Google Font / Sniglet",
  "Google Font / Snippet",
  "Google Font / Snowburst One",
  "Google Font / Sofadi One",
  "Google Font / Sofia",
  "Google Font / Song Myung",
  "Google Font / Sonsie One",
  "Google Font / Sorts Mill Goudy",
  "Google Font / Source Code Pro",
  "Google Font / Source Sans Pro",
  "Google Font / Source Serif Pro",
  "Google Font / Space Mono",
  "Google Font / Special Elite",
  "Google Font / Spectral",
  "Google Font / Spectral SC",
  "Google Font / Spicy Rice",
  "Google Font / Spinnaker",
  "Google Font / Spirax",
  "Google Font / Squada One",
  "Google Font / Sree Krushnadevaraya",
  "Google Font / Sriracha",
  "Google Font / Srisakdi",
  "Google Font / Staatliches",
  "Google Font / Stalemate",
  "Google Font / Stalinist One",
  "Google Font / Stardos Stencil",
  "Google Font / Stint Ultra Condensed",
  "Google Font / Stint Ultra Expanded",
  "Google Font / Stoke",
  "Google Font / Strait",
  "Google Font / Stylish",
  "Google Font / Sue Ellen Francisco",
  "Google Font / Suez One",
  "Google Font / Sumana",
  "Google Font / Sunflower",
  "Google Font / Sunshiney",
  "Google Font / Supermercado One",
  "Google Font / Sura",
  "Google Font / Suranna",
  "Google Font / Suravaram",
  "Google Font / Suwannaphum",
  "Google Font / Swanky and Moo Moo",
  "Google Font / Syncopate",
  "Google Font / Tajawal",
  "Google Font / Tangerine",
  "Google Font / Taprom",
  "Google Font / Tauri",
  "Google Font / Taviraj",
  "Google Font / Teko",
  "Google Font / Telex",
  "Google Font / Tenali Ramakrishna",
  "Google Font / Tenor Sans",
  "Google Font / Text Me One",
  "Google Font / Thasadith",
  "Google Font / The Girl Next Door",
  "Google Font / Tienne",
  "Google Font / Tillana",
  "Google Font / Timmana",
  "Google Font / Tinos",
  "Google Font / Titan One",
  "Google Font / Titillium Web",
  "Google Font / Tomorrow",
  "Google Font / Trade Winds",
  "Google Font / Trirong",
  "Google Font / Trocchi",
  "Google Font / Trochut",
  "Google Font / Trykker",
  "Google Font / Tulpen One",
  "Google Font / Turret Road",
  "Google Font / Ubuntu",
  "Google Font / Ubuntu Condensed",
  "Google Font / Ubuntu Mono",
  "Google Font / Ultra",
  "Google Font / Uncial Antiqua",
  "Google Font / Underdog",
  "Google Font / Unica One",
  "Google Font / UnifrakturCook",
  "Google Font / UnifrakturMaguntia",
  "Google Font / Unkempt",
  "Google Font / Unlock",
  "Google Font / Unna",
  "Google Font / VT323",
  "Google Font / Vampiro One",
  "Google Font / Varela",
  "Google Font / Varela Round",
  "Google Font / Vast Shadow",
  "Google Font / Vesper Libre",
  "Google Font / Vibes",
  "Google Font / Vibur",
  "Google Font / Vidaloka",
  "Google Font / Viga",
  "Google Font / Voces",
  "Google Font / Volkhov",
  "Google Font / Vollkorn",
  "Google Font / Vollkorn SC",
  "Google Font / Voltaire",
  "Google Font / Waiting for the Sunrise",
  "Google Font / Wallpoet",
  "Google Font / Walter Turncoat",
  "Google Font / Warnes",
  "Google Font / Wellfleet",
  "Google Font / Wendy One",
  "Google Font / Wire One",
  "Google Font / Work Sans",
  "Google Font / Yanone Kaffeesatz",
  "Google Font / Yantramanav",
  "Google Font / Yatra One",
  "Google Font / Yellowtail",
  "Google Font / Yeon Sung",
  "Google Font / Yeseva One",
  "Google Font / Yesteryear",
  "Google Font / Yrsa",
  "Google Font / ZCOOL KuaiLe",
  "Google Font / ZCOOL QingKe HuangYou",
  "Google Font / ZCOOL XiaoWei",
  "Google Font / Zeyada",
  "Google Font / Zhi Mang Xing",
  "Google Font / Zilla Slab",
  "Google Font / Zilla Slab Highlight",
];
