import { LanguageField, UidField, moduleBlocksField } from "./fields.js";
import { superClassFields } from "./superClassFields.js";
export const settings = {
  name: "settings",
  label: "Settings",
  delete: false,
  description:
    "The central place to configure your Website. Change your website's Theme here, edit the website title, site owner details, social media accounts and much more.",
  files: [
    {
      file: "/src/_data/pure-general-settings.json",
      label: "General",
      name: "general",
      fields: [
        {
          label: "Theme",
          name: "theme",
          required: true,
          widget: "relation",
          default: "default",
          collection: "themes",
          displayFields: ["title"],
          searchFields: ["title"],
          valueField: "uid",
          hint:
            "Changes here take effect after a rebuilt. This happens automatically in the background. To see a changed theme in layouts and pages, publish and reload the CMS a while later.",
        },
        LanguageField({}),
        {
          label: "Site Title",
          name: "sitetitle",
          widget: "string",
          default: "my new Website",
          hint: "insert into the page using {{sitetitle}}",
        },
        {
          label: "Site Tagline",
          name: "tagline",
          required: false,
          widget: "string",
          default: "with an awesome tagline",
          hint: "Name or Company, insert into the page using {{tagline}}",
        },
        //  {
        //    label: "Logo",
        //    widget: "image",
        //    required: false,
        //    name: "logo",
        //  },
        {
          label: "Site Owner",
          name: "siteowner",
          widget: "string",
          required: false,
          default: "Site Owner",
          hint: "Name or Company, insert into the page using {{siteowner}}",
        },
        {
          label: "E-mail",
          name: "email",
          widget: "string",
          required: false,
          default: "mail@example.com",
          hint: "Insert into the page using {{email}}",
        },
        {
          label: "Phone",
          name: "phone",
          widget: "string",
          required: false,
          default: "0123456789",
          hint: "Insert into the page using {{phone}}",
        },
        {
          label: "Address 1",
          name: "address1",
          widget: "string",
          required: false,
          default: "123 Main Road",
          hint: "Address line 1, insert into the page using {{address1}}",
        },
        {
          label: "Address 2",
          name: "address2",
          widget: "string",
          required: false,
          default: "45678 Anytown",
          hint: "Address line 2, insert into the page using {{address2}}",
        },
        {
          label: "Address 3",
          name: "address3",
          widget: "string",
          required: false,
          hint: "Address line 3, insert into the page using {{address3}}",
        },
        {
          label: "Address 4",
          name: "address4",
          widget: "string",
          required: false,
          hint: "Address line 4, insert into the page using {{address4}}",
        },
        {
          label: "Website",
          name: "website",
          required: false,
          widget: "string",
          hint: "Insert into the page using {{website}}",
        },
        {
          label: "Github Username",
          name: "github",
          required: false,
          widget: "string",
          hint: "Insert into the page using {{github}}",
        },
        {
          label: "Twitter Username",
          name: "twitter",
          required: false,
          widget: "string",
          hint: "Insert into the page using {{twitter}}",
        },
        {
          label: "Facebook Username",
          name: "facebook",
          required: false,
          widget: "string",
          hint: "Insert into the page using {{facebook}}",
        },
        {
          label: "Instagram Username",
          name: "instagram",
          required: false,
          widget: "string",
          hint: "Insert into the page using {{instagram}}",
        },
      ],
    },
    {
      file: "/src/_data/pure-seo.json",
      label: "Search Engine Optimization",
      name: "seo",
      fields: [
        {
          label: "Title",
          name: "title",
          required: true,
          widget: "string",
        },
        {
          label: "Responsive Images",
          name: "responsive-images",
          required: false,
          widget: "boolean",
          default: true,
        },
        {
          label: "Progressive Web App",
          name: "progressive-web-app",
          required: false,
          widget: "boolean",
          default: true,
        },
      ],
    },
    {
      file: "/src/_data/pure-super-classes.json",
      label: "Modules",
      name: "superClasses",
      fields: [
        {
          label: "Modules",
          label_singular: "Module",
          name: "superClasses",
          widget: "list",
          collapsed: true,
          allow_add: true,
          fields: [
            {
              label: "Title",
              name: "title",
              pattern: [
                "^([a-z])([a-z0-9]+)?$",
                "just lowercase or numbers and start with a letter",
              ],
              widget: "string",
              default: "newclass",
            },
            {
              label: "Background Video",
              widget: "file",
              required: false,
              name: "video",
            },
            {
              label: "default",
              name: "xs",
              widget: "object",
              fields: superClassFields,
            },
            {
              label: "SM and up",
              name: "sm",
              widget: "object",
              collapsed: true,
              fields: superClassFields,
            },
            {
              label: "MD and up",
              name: "md",
              widget: "object",
              collapsed: true,
              fields: superClassFields,
            },
            {
              label: "LG and up",
              name: "lg",
              widget: "object",
              collapsed: true,
              fields: superClassFields,
            },
            {
              label: "XL and up",
              name: "xl",
              widget: "object",
              collapsed: true,
              fields: superClassFields,
            },
            moduleBlocksField,
            UidField({}),
          ],
        },
      ],
    },
  ],
};
